# https://arduino.github.io/arduino-cli/latest/library-specification/
name=imxrt1060-regs
version=0.1.0-snapshot
author=Shawn Silverman <shawn@pobox.com>
maintainer=Shawn Silverman <shawn@pobox.com>
sentence=A new and more modern way to access and modify registers.
paragraph=This library uses modern C++ features to avoid defines, macros, and other avoidable mistakes. It compiles to code as efficient as using addresses, shifts, and masks.
category=Data Processing
url=https://github.com/ssilverman/imxrt1060-regs
architectures=*
includes=imxrt1060_regs.h
