; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[common]
build_flags = -g -Og -Wvla -Werror

[teensy-base]
platform = teensy
framework = arduino
monitor_speed = 115200
build_unflags = -fpermissive -Wno-error=narrowing -Wno-maybe-uninitialized
build_flags = ${common.build_flags} -DIMXRT1060REGS_MAIN_TEST_PROGRAM

[env:teensy41]
extends = teensy-base
board = teensy41

[env:teensy40]
extends = teensy-base
board = teensy40
